name: Action Server manual Brew publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to upload'
        required: true
        default: 'x.x.x'

jobs:
  action-server:
    name: action-server
    runs-on: macos-13
    steps:
      - name: main checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "kari@robocorp.com"
          git config --global user.name "kariharju"

      - name: Update cask recipe
        run: |
          cd scripts
          chmod 755 ./homebrew-update.sh
          ./homebrew-update.sh ${{ github.event.inputs.version }}

      - name: Check Homebrew Formula
        run: |
          brew audit --new Casks/action-server.rb
          brew style Casks/action-server.rb

      - name: Install and Test Cask
        run: |
          brew install --cask Casks/action-server.rb
          action-server version

      - name: Commit and Push
        run: |
          git add Casks/action-server.rb
          git commit -m "Update Action Server to version ${{ github.event.inputs.version }}"
          git push
